Kernel360/KBE5_DANMUJI_BE

- module-api/src/main/resources/application-dev.yml
ec2에 dev용 db 설치/세팅
- application-dev.yml 추가
- Close #4
- 각자 로컬 개발 환경에서 .env수정, profiles 수정 필요합니다.
```
DB_HOST={EC2_Public_IP}
DB_PORT=3306
DB_SCHEME={공지참고}
DB_USER={공지참고}
DB_PASSWORD={공지참고}
```
> chore: dev용 yml생성(ec2 db) Close #4

- module-application/build.gradle
module-application에 mysql의존성 추가
- module-application에 mysql의존성 추가
- Close #5 
- See also #
> chore: mysql 의존성 추가 (#4)

- module-jpa/src/main/java/com/back2basics/common/entity/common/BaseTimeEntity.java
- 공통 사용을 위한 패키지(Common)을 생성하고 BaseEntity를 /Common 로 이동하였습니다.
- Common 패키지 생성
- BaseEntity 위치 변경 (/Common으로)
- Close #10 
- See also #
> refactor: BaseEntity를 Common 패키지로 이동 (#10)

- module-core/src/main/java/com/back2basics/infra/custom/CustomNotBlankValidator.java
- module-core/src/main/java/com/back2basics/infra/custom/CustomTitleNotBlank.java
- module-core/src/main/java/com/back2basics/infra/validation/PostValidator.java
- module-core/src/main/java/com/back2basics/model/post/Post.java
- module-core/src/main/java/com/back2basics/port/in/post/DeletePostUseCase.java
- module-core/src/main/java/com/back2basics/port/in/post/GetPostUseCase.java
- module-core/src/main/java/com/back2basics/port/out/post/PostRepositoryPort.java
- module-core/src/main/java/com/back2basics/service/post/PostServiceImpl.java
- module-core/src/main/java/com/back2basics/service/post/dto/PostResponseDto.java
- module-core/src/main/java/com/back2basics/service/post/dto/PostUpdateCommand.java
- module-core/src/main/java/com/back2basics/service/post/exception/PostErrorCode.java
- module-core/src/main/java/com/back2basics/service/post/validation/PostValidator.java
- module-jpa/src/main/java/com/back2basics/post/entity/PostEntity.java
- module-jpa/src/main/java/com/back2basics/post/mapper/PostMapper.java
- module-jpa/src/main/java/com/back2basics/post/repository/PostEntityRepository.java
- module-web/src/main/java/com/back2basics/post/controller/PostController.java
- #28 의 코멘트 요청 사항에 대한 작업을 완료하였습니다.
- Update 시 발생할 수 있는 내용을 수정하였습니다.
- 커스텀 어노테이션과 관련된 작업을 module-core/infra/.. 에 위치시켰습니다.
언급한 커스텀 어노테이션 추가하는 방법으로 해결하였습니다.
아래는 동작 확인입니다.
> [Fix] 코멘트 이슈 반영 

- module-core/src/main/java/com/back2basics/model/post/Post.java
- module-core/src/main/java/com/back2basics/port/in/post/DeletePostUseCase.java
- module-core/src/main/java/com/back2basics/port/in/post/GetPostUseCase.java
- module-core/src/main/java/com/back2basics/port/out/post/PostRepositoryPort.java
- module-core/src/main/java/com/back2basics/service/post/PostServiceImpl.java
- module-core/src/main/java/com/back2basics/service/post/dto/PostResponseDto.java
- module-core/src/main/java/com/back2basics/service/post/dto/PostUpdateCommand.java
- module-core/src/main/java/com/back2basics/service/post/exception/PostErrorCode.java
- module-core/src/main/java/com/back2basics/service/post/validation/PostValidator.java
- module-jpa/src/main/java/com/back2basics/post/entity/PostEntity.java
- module-jpa/src/main/java/com/back2basics/post/mapper/PostMapper.java
- module-jpa/src/main/java/com/back2basics/post/repository/PostEntityRepository.java
- module-web/src/main/java/com/back2basics/post/controller/PostController.java
- 변수 명, 테이블 명 수정하였습니다.
- 모든 파일에 대해 google formatter 적용하였습니다.
- 수정, 삭제 메소드를 수정하였습니다.
- 다음 해결해야 할 일을 todo 주석에 작성하였습니다.
- 변수명 수정 :
-  Controller에서 파라미터를 postId로 변경하였습니다. (value =`/posts/{id}` -> `/posts/{postId}`)
- PostEntity 수정
- `@Table(name = post)` -> `@Table(name = posts)`
- 수정, 삭제 메소드 수정
- 작성자 일치 검증, 게시글 존재 여부 검증 추가 
- HTTP Patch 요청답게 수정
- 특정 필드를 전달하지 않을 경우 `@NotBlank`에 의해 걸리지 않도록 validation 조건 수정하였습니다.
- todo 주석 추가 
- 가까운 시일 내에 해야할 작업 위주로 작성하였습니다.
- #27 
- `Insomnia` 사용하여 HTTP Request 테스트만 진행하였습니다.
- `Insomnia` 는 포스트맨같은건데 ui가 깔끔해서 꽤 편리합니다. 
- 또 api docs 생성 기능이 있어서 swagger 대신에 활용하기에 좋을 것 같습니다. 
- 추가로 공동 작업도 가능하니 도입에 대해 논의하면 좋을 것 같습니다.
> [Feature] 게시글 기능 

- module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
- module-core/src/main/java/com/back2basics/project/port/in/ReadProjectUseCase.java
- module-core/src/main/java/com/back2basics/project/port/out/ReadProjectPort.java
- module-core/src/main/java/com/back2basics/project/port/out/SaveProjectPort.java
- module-core/src/main/java/com/back2basics/project/port/out/UpdateProjectPort.java
- module-core/src/main/java/com/back2basics/project/service/CreateProjectService.java
- module-core/src/main/java/com/back2basics/project/service/DeleteProjectService.java
- module-core/src/main/java/com/back2basics/project/service/ProjectServiceImpl.java
- module-core/src/main/java/com/back2basics/project/service/ReadProjectService.java
- module-core/src/main/java/com/back2basics/project/service/UpdateProjectService.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/ReadProjectAdapter.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/SaveProjectAdapter.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/UpdateProjectAdapter.java
- port 분리
- adapter 분리
- service 분리
- port 분리
- adapter 분리
- service 분리
- Close #88
- See also #
> [Refactor] 변경된 프로젝트 구조에 맞게 수정

- module-api/src/main/java/com/back2basics/domain/company/controller/CompanyController.java
- module-api/src/main/java/com/back2basics/domain/company/dto/request/UpdateCompanyRequest.java
- module-core/src/main/java/com/back2basics/company/port/in/command/UpdateCompanyCommand.java
- module-core/src/main/java/com/back2basics/company/port/out/CompanyRepositoryPort.java
- module-core/src/main/java/com/back2basics/company/port/out/UpdateCompanyPort.java
- module-core/src/main/java/com/back2basics/company/service/CompanyServiceImpl.java
- module-core/src/main/java/com/back2basics/company/service/UpdateCompanyService.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/company/CompanyJpaAdapter.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/company/adapter/UpdateCompanyJpaAdapter.java
Company 수정 기능 분리 작업
UpdateCompanyPort, UpdateCompanyService, UpdateCompanyRequest(result, response 불필요) 
UpdateCompanyJpaAdapter 생성
CompanyController 수정
- Close #97 
Talend API로 수정 확인
> [Refactor] Company 수정 기능 분리 작업

- module-core/src/main/java/com/back2basics/company/port/out/DeleteCompanyPort.java
- module-core/src/main/java/com/back2basics/company/service/DeleteCompanyService.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/company/adapter/DeleteCompanyJpaAdapter.java
Company 삭제 기능 분리 작업
delete에서 별도의 Response 필요 X, Request, Command, Result, Response 전부 필요없음.
- Close #98 
Talend API 정상 동작 확인
> [Refactor] Company 삭제 기능 분리 작업

- module-api/src/main/java/com/back2basics/domain/comment/dto/request/CommentCreateRequest.java
- module-api/src/main/java/com/back2basics/domain/comment/dto/request/CommentDeleteRequest.java
- module-api/src/main/java/com/back2basics/domain/comment/dto/request/CommentUpdateRequest.java
- module-api/src/test/java/com/back2basics/comment/model/CommentTest.java
- module-api/src/test/java/com/back2basics/comment/service/CommentCreateServiceTest.java
- module-api/src/test/java/com/back2basics/comment/service/CommentUpdateServiceTest.java
- module-core/src/main/java/com/back2basics/comment/model/Comment.java
- module-core/src/main/java/com/back2basics/comment/port/in/CommentCreateUseCase.java
- module-core/src/main/java/com/back2basics/comment/port/in/CommentUpdateUseCase.java
- module-core/src/main/java/com/back2basics/comment/port/in/command/CommentCreateCommand.java
- module-core/src/main/java/com/back2basics/comment/port/in/command/CommentDeleteCommand.java
- module-core/src/main/java/com/back2basics/comment/port/in/command/CommentUpdateCommand.java
- module-core/src/main/java/com/back2basics/comment/service/CommentCreateService.java
- module-core/src/main/java/com/back2basics/comment/service/CommentModelRelationHelper.java
- module-core/src/main/java/com/back2basics/comment/service/CommentUpdateService.java
- 디렉토리 위치 실수
- 잘못된 디렉토리 위치를 수정합니다.
- #122
> [Fix] 댓글 command 디렉토리 위치 실수 수정 (#122)

- module-api/src/main/java/com/back2basics/domain/comment/controller/CommentController.java
- module-api/src/main/java/com/back2basics/domain/comment/swagger/CommentApiDocs.java
- module-api/src/main/java/com/back2basics/domain/comment/swagger/CommentDocsResult.java
- module-api/src/main/java/com/back2basics/domain/post/controller/PostController.java
- module-api/src/main/java/com/back2basics/domain/post/swagger/PostApiDocs.java
- module-api/src/main/java/com/back2basics/domain/post/swagger/PostDocsResult.java
- 댓글 swagger ui 적용
- 게시글 swagger ui 수정
- 댓글 생성,수정,삭제 swagger ui 적용
- 게시글 조회 시 댓글이 나오도록 수정
- 디렉토리 이름 수정 docs -> swagger
- Close #125 
- See also #106 
- 반복되는 내용이 많아 ai를 활용했는데, 꼼꼼히 체크해보셔야할것같습니다.
> [Docs] 댓글 swagger ui 적용 및 게시글 swagger 응답 형식 수정

- module-api/src/main/java/com/back2basics/domain/company/controller/CompanyController.java
- module-core/src/main/java/com/back2basics/company/model/Company.java
회사 수정 HTTP 메서드 PATCH에서 PUT으로 수정
회사 수정 HTTP 메서드 PATCH에서 PUT으로 수정
도메인 객체 내 비즈니스 로직에서 null값을 체크하여 변경하던 것과 달리
전부 변경하도록 함.
- Close #141
Talend API 정상 동작 확인
> [Feature] 회사 수정 HTTP 메서드 PATCH에서 PUT으로 수정

- module-api/src/main/java/com/back2basics/domain/projectstep/controller/ProjectStepController.java
- module-core/src/main/java/com/back2basics/project/service/CreateProjectService.java
- module-core/src/main/java/com/back2basics/projectstep/model/ProjectStep.java
- module-core/src/main/java/com/back2basics/projectstep/port/in/DeleteProjectStepUseCase.java
- module-core/src/main/java/com/back2basics/projectstep/service/CreateProjectStepService.java
- module-core/src/main/java/com/back2basics/projectstep/service/DeleteProjectStepService.java
- module-core/src/main/java/com/back2basics/projectstep/service/result/ReadProjectStepResult.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/projectstep/ProjectStepEntity.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/projectstep/ProjectStepEntityRepository.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/projectstep/ProjectStepMapper.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/projectstep/adapter/ReadProjectStepAdapter.java
프로젝트 단계 D 구현
- 프로젝트 단계 삭제 구현을 위한 필드 추가
- 삭제 구현
- 삭제 되지 않은 단계만 조회
- 임시 userId로 프로젝트단계 생성
- Close #116
- See also #
- postman 테스트 모든 api 정상작동
코드 수정이 많을 예정이라 바로 머지하겠습니다.
또한 리뷰하신다면 주석은 그냥 다 무시해주세요!
> [Feature] 프로젝트 단계 삭제 구현

- module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
- module-api/src/main/java/com/back2basics/domain/projectstep/controller/ProjectStepController.java
- module-api/src/main/java/com/back2basics/domain/projectstep/controller/code/ProjectStepResponseCode.java
- module-core/src/main/java/com/back2basics/infra/exception/projectstep/ProjectStepException.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/projectstep/adapter/ReadProjectStepAdapter.java
에러메세지 수정 및 http 메서드 변경
- [] 리팩토링 (Refactor)
에러메세지 수정 및 http 메서드 변경
- Close #
- See also #
push 했는데 pr이 안떠서 테스트 브랜치로 하나 파서 다시 push 했습니다.
> [Fix] 에러메세지 수정 및 http 메서드 변경

- module-api/src/main/java/com/back2basics/domain/user/controller/AdminController.java
- module-api/src/main/java/com/back2basics/domain/user/dto/response/UserCreateResponse.java
- module-api/src/main/java/com/back2basics/domain/user/dto/response/UserInfoResponse.java
- module-api/src/test/java/com/back2basics/security/LoginFailTest.java
- module-api/src/test/java/com/back2basics/security/LoginSuccessTest.java
- module-api/src/test/java/com/back2basics/security/LogoutTest.java
- module-api/src/test/java/com/back2basics/security/ReissueFailTest.java
- module-api/src/test/java/com/back2basics/security/ReissueSuccessTest.java
- module-core/src/main/java/com/back2basics/user/model/User.java
- module-core/src/main/java/com/back2basics/user/service/CreateUserService.java
- module-core/src/main/java/com/back2basics/user/service/UserQueryService.java
- module-core/src/main/java/com/back2basics/user/service/result/UserCreateResult.java
- module-core/src/main/java/com/back2basics/user/service/result/UserInfoResult.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/user/adapter/out/UserJpaAdapter.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/user/mapper/UserMapper.java
- user save 로직 변경
- save 시 userMapper에서 companyEntity 조회 -> service 단에서 companyEntity 조회
- result 클래스 record로 전환
- Close #168
> [FIX] user - company 매핑 수정 (#168)

- module-api/src/main/java/com/back2basics/domain/user/dto/request/UserCreateRequest.java
- module-api/src/main/java/com/back2basics/domain/user/dto/response/UserInfoResponse.java
- module-core/src/main/java/com/back2basics/user/model/User.java
- module-core/src/main/java/com/back2basics/user/model/UserType.java
- module-core/src/main/java/com/back2basics/user/port/in/command/UserCreateCommand.java
- module-core/src/main/java/com/back2basics/user/service/UserQueryService.java
- module-core/src/main/java/com/back2basics/user/service/result/UserInfoResult.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/user/adapter/out/UserJpaAdapter.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/user/entity/UserEntity.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/user/mapper/UserMapper.java
- 회원 생성 로직 수정
- 조회 로직 수정
- userType enum class 추가
- 조회 시 생성일자, 수정일자 포함
- Close #170 
- Close #171
- Close #172 
- See also #
> [Feature]  user 개발사 담당자, 고객사 담당자 필드 추가 및 조회 시 생성일자, 수정일자 포함

- module-api/src/main/java/com/back2basics/global/security/config/SecurityConfig.java
- Swagger 사용을 위해 SecurityConfig 수정
- SecurityConfig에 swaggerUrls 추가
- 전체 접근 허용 API 수정
- Close #175
> [Feature] Swagger 사용을 위해 SecurityConfig 수정

- module-api/src/main/java/com/back2basics/domain/company/controller/CompanyController.java
- module-core/src/main/java/com/back2basics/company/port/in/ReadCompanyUseCase.java
- module-core/src/main/java/com/back2basics/company/port/out/ReadCompanyPort.java
- module-core/src/main/java/com/back2basics/company/service/ReadCompanyService.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/company/CompanyEntityRepository.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/company/adapter/ReadCompanyJpaAdapter.java
이름으로 검색 가능하게 함(검색창 기능)
softDelete된 데이터들은 조회되지 않게 쿼리 수정
이름으로 검색 가능하게 함(검색창 기능)
softDelete된 데이터들은 조회되지 않게 쿼리 수정
- Close #157 
예상 값 : tes가 들어가있는건 모두 조회되어야 하며, softDelete로 deletedAt이 Null이 아닌 것들(삭제 일시가 찍힌)은 조회되면 안된다.
tes가 들어간 데이터들이 조회 된다.
softdelete가 된 1, 5는 제외하고 2, 3, 4만 조회된 것을 알 수 있다.
> [Feature] 회사 검색 기능 세부 수정

- module-api/src/main/java/com/back2basics/domain/user/controller/UserController.java
- module-core/src/main/java/com/back2basics/user/port/in/ChangePasswordUseCase.java
- module-core/src/main/java/com/back2basics/user/port/in/UserQueryUseCase.java
- module-core/src/main/java/com/back2basics/user/service/ChangePasswordService.java
- module-core/src/main/java/com/back2basics/user/service/UserQueryService.java
- userController 로직 수정
- 필요없는 Query method 삭제
- UserController에서 Principal 을 CustomUserDetails를 받도록 수정했습니다.
- principal에서는 name 값만 받을 수 있기 때문에 생성한 findByUsername 메서드를 삭제하고 customUserDetails에서 id 값을 받아 findById 를 사용했습니다.
- Close #194 
- See also #178
> [Refactor] principal -> CustomUserDetails 사용

- module-api/src/main/java/com/back2basics/domain/post/swagger/PostDocsResult.java
- module-api/src/main/java/com/back2basics/domain/question/swagger/QuestionDocsResult.java
- module-infra/src/main/java/com/back2basics/config/SwaggerConfig.java
- post 요청 누락 필드 추가, 안쓰는 상수값 삭제
- security 도입에 따른 swagger 수정 : 헤더에 인증 토큰 넣을 수 있게 수정
- post 요청 누락 필드 추가, 안쓰는 상수값 삭제
- security 도입에 따른 swagger 수정 : 헤더에 인증 토큰 넣을 수 있게 수정
- Close #206 
- Close #207
> [Docs] Swagger 수정

- module-api/src/main/java/com/back2basics/domain/company/controller/CompanyController.java
- module-core/src/main/java/com/back2basics/company/port/in/ReadCompanyUseCase.java
- module-core/src/main/java/com/back2basics/company/service/ReadCompanyService.java
- module-core/src/main/java/com/back2basics/infra/validation/validator/CompanyValidator.java
- module-core/src/main/java/com/back2basics/user/port/out/UserQueryPort.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/user/adapter/out/UserQueryAdapter.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/user/entity/UserEntity.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/user/mapper/UserMapper.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/user/repository/UserEntityRepository.java
- 회사 내의 유저 조회 기능 추가
- 회사 내 직원 조회 API 추가
- 서비스 로직 구현
- 회사 validator 추가
- UserEntity 내의 CompanyEntity 필드명 변경
- Close #234 
- See also #222
> [Feature] 회사 직원 조회 API

- module-core/src/main/java/com/back2basics/user/service/UserQueryService.java
- module-core/src/main/java/com/back2basics/user/service/result/UserInfoResult.java
- module-core/src/main/java/com/back2basics/user/service/result/UserSimpleResult.java
- 유저 조회 API 리팩토링
- 조회 시 중복 로직을 수정했습니다.
- Close #241 
- See also #222 
- 정적 팩토리 메서드 규칙에 따르면 `from = 단일 타입 변환` , `of = 복수 인자 조합`이 권장된다고 합니다.
- 참고 부탁드립니다.
> refactor: 정적 팩토리 메서드 규칙에 따라 리팩토링

- .github/workflows/deploy.yml
> [Feature] Create deploy.yml

- module-api/src/main/java/com/back2basics/domain/answer/swagger/AnswerApiDocs.java
- module-api/src/main/java/com/back2basics/domain/answer/swagger/AnswerDocsResult.java
- module-api/src/main/java/com/back2basics/domain/comment/swagger/CommentApiDocs.java
- module-api/src/main/java/com/back2basics/domain/comment/swagger/CommentDocsResult.java
- module-api/src/main/java/com/back2basics/domain/post/swagger/PostDocsResult.java
- module-api/src/main/java/com/back2basics/domain/question/swagger/QuestionDocsResult.java
- swagger json 포맷 오류 수정
- 누락된 응답 필드 추가
- swagger json 포맷 오류 수정
- 누락된 응답 필드 추가
- See also #246
> [Docs] swagger 응답에 json 포맷 오류 수정

- module-api/src/main/java/com/back2basics/global/security/config/SecurityConfig.java
> [Feature] 허용 도메인 수정

- module-api/src/main/java/com/back2basics/global/security/config/SecurityConfig.java
- module-infra/src/main/java/com/back2basics/util/CookieUtil.java
- cookieutil 수정
- 프론트와 연동을 위해 `cookie.setSecure(true)` 설정
- Close #251 
- See also #
> [Feature] cookie 설정 수정 

- module-api/src/main/java/com/back2basics/domain/company/dto/request/CreateCompanyRequest.java
- module-api/src/main/java/com/back2basics/domain/company/dto/request/UpdateCompanyRequest.java
- module-api/src/main/java/com/back2basics/domain/company/dto/response/ReadCompanyResponse.java
- module-core/src/main/java/com/back2basics/company/model/Company.java
- module-core/src/main/java/com/back2basics/company/port/in/command/CreateCompanyCommand.java
- module-core/src/main/java/com/back2basics/company/port/in/command/UpdateCompanyCommand.java
- module-core/src/main/java/com/back2basics/company/service/result/ReadCompanyResult.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/company/CompanyEntity.java
사업자 등록번호 타입 Integer에서 Long으로 변경
사업자 등록번호 타입 Integer에서 Long으로 변경
Integer범위 때문에 '999-99-99999'등이 입력되지 않았었음.
- Close #264
회사 등록 시 사업자 등록번호 입력
정상 동작 확인
> [Feature] Company bizNo(사업자 등록번호) 타입 변경

- module-api/src/main/java/com/back2basics/domain/company/controller/CompanyController.java
- module-core/src/main/java/com/back2basics/company/port/in/ReadCompanyUseCase.java
- module-core/src/main/java/com/back2basics/company/port/out/ReadCompanyPort.java
- module-core/src/main/java/com/back2basics/company/service/ReadCompanyService.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/company/CompanyEntityRepository.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/company/adapter/ReadCompanyJpaAdapter.java
Company Pagenation없는 조회 추가
Company Pagenation없는 조회 추가
- Close #279 
Postman으로 요청 시 Pagenation없이 조회되는 모습 확인
> [Feature] Company Pagenation없는 조회 추가

- module-core/src/main/java/com/back2basics/company/port/out/CreateCompanyPort.java
- module-core/src/main/java/com/back2basics/company/service/CreateCompanyService.java
- module-core/src/main/java/com/back2basics/infra/exception/company/CompanyErrorCode.java
- module-core/src/main/java/com/back2basics/infra/exception/company/DuplicateCompanyNameException.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/company/CompanyEntity.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/company/CompanyEntityRepository.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/company/adapter/CreateCompanyJpaAdapter.java
엔티티 unique = true 추가 및 오류 처리
엔티티 unique = true 추가 및 오류 처리
Service에서 중복확인 하도록 했음.
- Close #287 
postman 및 로컬 환경 FE에서 확인
> [Feature] 회사명 중복 방지

- module-api/src/main/java/com/back2basics/domain/project/dto/response/ProjectGetResponse.java
- module-core/src/main/java/com/back2basics/project/model/Project.java
- module-core/src/main/java/com/back2basics/project/service/ReadProjectService.java
- module-core/src/main/java/com/back2basics/project/service/result/ProjectGetResult.java
- module-core/src/main/java/com/back2basics/projectuser/service/result/ReadProjectUserResult.java
프로젝트 response 변경
- Close #
- See also #
> [Feature] 프로젝트 response 변경

- module-api/src/main/java/com/back2basics/domain/auth/AuthService.java
- module-api/src/main/java/com/back2basics/domain/auth/controller/AuthController.java
- module-api/src/main/java/com/back2basics/domain/project/dto/response/ProjectGetResponse.java
- module-api/src/main/java/com/back2basics/domain/user/dto/response/UserInfoResponse.java
- module-core/src/main/java/com/back2basics/project/model/Project.java
- module-core/src/main/java/com/back2basics/project/service/ReadProjectService.java
- module-core/src/main/java/com/back2basics/project/service/result/ProjectGetResult.java
- module-core/src/main/java/com/back2basics/projectuser/service/result/ReadProjectUserResult.java
- module-core/src/main/java/com/back2basics/user/model/User.java
- module-core/src/main/java/com/back2basics/user/port/in/UpdateUserUseCase.java
- module-core/src/main/java/com/back2basics/user/service/UpdateUserService.java
- module-core/src/main/java/com/back2basics/user/service/result/UserInfoResult.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/user/entity/UserEntity.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/user/mapper/UserMapper.java
- 마지막 로그인 일자 추가
- 마지막 로그인 일자 필드 추가
- 조회 시 반환
- Close #290 
- See also #
> [Feature] 마지막 로그인 정보 추가

- module-api/src/main/java/com/back2basics/global/handler/GlobalExceptionHandler.java
customUserDetails가 null일때 글로벌예외 등록(임시) 
- `GlobalExceptionHandler`에 customUserDetails가 null일때 글로벌예외로 잡을 수 있도록 추가했습니다.
- 기타 시큐리티에 의한 인증/인가 예외는 필터로 등록해서 잡아줘야하기때문에 추후에 작업 예정입니다.
- Close #291
> [Feature] customUserDetails가 null일때 글로벌예외 등록(임시) 

- module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
- module-api/src/main/java/com/back2basics/domain/projectstep/controller/ProjectStepController.java
- module-api/src/main/java/com/back2basics/domain/projectstep/controller/code/ProjectStepResponseCode.java
- module-api/src/main/java/com/back2basics/domain/projectstep/dto/response/DetailProjectStepResponse.java
- module-core/src/main/java/com/back2basics/project/port/in/ReadProjectUseCase.java
- module-core/src/main/java/com/back2basics/project/port/out/ReadProjectPort.java
- module-core/src/main/java/com/back2basics/project/service/ReadProjectService.java
- module-core/src/main/java/com/back2basics/project/service/result/ProjectGetResult.java
- module-core/src/main/java/com/back2basics/projectstep/model/ProjectStep.java
- module-core/src/main/java/com/back2basics/projectstep/port/in/ReadProjectStepUseCase.java
- module-core/src/main/java/com/back2basics/projectstep/port/out/ReadProjectStepPort.java
- module-core/src/main/java/com/back2basics/projectstep/service/ReadProjectStepService.java
- module-core/src/main/java/com/back2basics/projectstep/service/result/DetailProjectStepResult.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectEntityRepository.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/ReadProjectAdapter.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/projectstep/ProjectStepEntity.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/projectstep/ProjectStepMapper.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/projectuser/ProjectUserEntityRepository.java
- 회원별 프로젝트 목록  조회
- 프로젝트 단계 상세 조회
- 회원별 프로젝트 목록 api
- 프로젝트 단계 상세 조회
- 응답객체 생성
- api 구현 
- Close #
- See also #
postman 조회 확인
> [Feature] 회원별 프로젝트 목록 및 프로젝트 단계 상세 조회

- module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
- module-api/src/main/java/com/back2basics/domain/project/controller/code/ProjectResponseCode.java
- module-api/src/main/java/com/back2basics/domain/project/dto/request/ProjectCreateRequest.java
- module-core/src/main/java/com/back2basics/project/port/in/command/ProjectCreateCommand.java
- module-core/src/main/java/com/back2basics/project/service/CreateProjectService.java
- module-core/src/main/java/com/back2basics/projectuser/model/ProjectUser.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/projectuser/ProjectUserEntity.java
프로젝트 멤버 할당
- [] 문서 수정 (Docs)
- request 필드 추가
- service 로직 변경
- 에러코드 status 변경
- Close #
- See also #
> [Feature] 프로젝트 멤버 할당

- module-api/src/main/java/com/back2basics/domain/user/dto/response/UserInfoResponse.java
- module-api/src/main/java/com/back2basics/domain/user/dto/response/UserSimpleResponse.java
- 조회 시 잘못된 시간대 반환을 수정
- 기대 값
- 반환 값
- JsonFormat에 시간대 옵션을 주지 않아 브라우저가 UTC로 해석함
- Close #317 
- See also #
> [Fix] 잘못된 시간대 반환 수정

- module-api/src/main/java/com/back2basics/domain/company/controller/CompanyController.java
- module-api/src/main/java/com/back2basics/domain/company/dto/response/ReadRecentCompanyResponse.java
- module-core/src/main/java/com/back2basics/company/port/in/ReadCompanyUseCase.java
- module-core/src/main/java/com/back2basics/company/port/out/ReadCompanyPort.java
- module-core/src/main/java/com/back2basics/company/service/ReadCompanyService.java
- module-core/src/main/java/com/back2basics/company/service/result/ReadRecentCompanyResult.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/company/CompanyEntityRepository.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/company/CompanyMapper.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/company/adapter/ReadCompanyJpaAdapter.java
관리자 대시보드 최근 등록된 회사 기능 구현
관리자 대시보드 최근 등록된 회사 기능 구현
- Close #322
> [Feature] 관리자 대시보드 최근 등록된 회사 기능 구현

- module-core/src/main/java/com/back2basics/company/service/DeleteCompanyService.java
- module-core/src/main/java/com/back2basics/user/port/out/UserCommandPort.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/user/adapter/out/UserCommandAdapter.java
회사 softDelete시 해당 회사에 속한 회원 softDelete 적용 기능 구현
회사 softDelete시 해당 회사에 속한 회원 softDelete 적용 기능 구현
- Close #332 
react 연동 후 테스트 결과 정상 작동
> [Feature] 회사 softDelete시 해당 회사에 속한 회원 softDelete 적용 기능 구현

- module-api/src/main/java/com/back2basics/domain/post/controller/PostController.java
- module-api/src/main/java/com/back2basics/domain/post/dto/response/ReadRecentPostResponse.java
- module-core/src/main/java/com/back2basics/post/port/in/PostReadUseCase.java
- module-core/src/main/java/com/back2basics/post/port/out/PostReadPort.java
- module-core/src/main/java/com/back2basics/post/service/PostReadService.java
- module-core/src/main/java/com/back2basics/post/service/result/ReadRecentPostResult.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/post/adapter/PostReadJpaAdapter.java
Post 최근 등록 5개 기능 구현
Post 최근 등록 5개 기능 구현
querydsl에 맞춰 구현
- Close #326 
리액트로 정상작동 확인
> [Feature] Post 최근 등록 5개 기능 구현

- module-infra/src/main/java/com/back2basics/adapter/persistence/company/CompanyEntity.java
회사 테이블 명 company -> companies 변경
회사 테이블 명 company -> companies 변경
- Close #297
> [Refactor] 회사 테이블 명 변경

- module-api/src/main/java/com/back2basics/domain/post/controller/PostController.java
- module-api/src/main/java/com/back2basics/domain/post/dto/response/PostDetailReadResponse.java
- module-api/src/main/java/com/back2basics/domain/post/dto/response/PostReadResponse.java
- module-api/src/main/java/com/back2basics/domain/post/dto/response/PostSummaryReadResponse.java
- module-api/src/main/java/com/back2basics/domain/post/swagger/PostApiDocs.java
- module-api/src/test/java/com/back2basics/post/service/PostReadServiceTest.java
- module-core/src/main/java/com/back2basics/post/model/Post.java
- module-core/src/main/java/com/back2basics/post/port/in/PostReadUseCase.java
- module-core/src/main/java/com/back2basics/post/port/in/PostSearchUseCase.java
- module-core/src/main/java/com/back2basics/post/service/PostReadService.java
- module-core/src/main/java/com/back2basics/post/service/PostSearchService.java
- module-core/src/main/java/com/back2basics/post/service/result/PostDetailReadResult.java
- module-core/src/main/java/com/back2basics/post/service/result/PostReadResult.java
- module-core/src/main/java/com/back2basics/post/service/result/PostSummaryReadResult.java
- module-core/src/main/java/com/back2basics/project/model/ProjectStatus.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/post/PostEntity.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/post/PostMapper.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/post/adapter/PostReadJpaAdapter.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/post/adapter/PostSearchJpaAdapter.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/post/adapter/projection/PostDetailResult.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/post/adapter/projection/PostSummaryResult.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectEntity.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectMapper.java
게시글 원하는 필드만 리턴, 프로젝트 기한 지나면 지연 상태로 변경
- Close #357 
- See also #
> [Feature] 게시글 원하는 필드만 리턴, 프로젝트 기한 지나면 지연 상태로 변경

- module-api/src/main/java/com/back2basics/domain/assignment/controller/AssignmentController.java
- module-api/src/main/java/com/back2basics/domain/assignment/controller/code/AssignmentResponseCode.java
- module-core/src/main/java/com/back2basics/assignment/model/Assignment.java
- module-core/src/main/java/com/back2basics/assignment/port/in/DeleteAssignmentUseCase.java
- module-core/src/main/java/com/back2basics/assignment/port/out/AssignmentQueryPort.java
- module-core/src/main/java/com/back2basics/assignment/port/out/DeleteAssignmentPort.java
- module-core/src/main/java/com/back2basics/assignment/service/DeleteAssignmentService.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/assignment/AssignmentEntityRepository.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/assignment/AssignmentMapper.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/assignment/adapter/AssignmentQueryAdapter.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/assignment/adapter/DeleteAssignmentAdapter.java
- 프로젝트 수정 시 할당된 업체 삭제 기능 구현
- projectId, companyId로 assignmnet 리스트 조회 후 전체 삭제
- Close #
- See also #
> [Feature] 프로젝트에 할당된 업체 삭제

- module-api/src/main/java/com/back2basics/domain/post/controller/PostController.java
- module-api/src/main/java/com/back2basics/domain/post/swagger/PostApiDocs.java
> [Docs] post swagger 업데이트

- module-core/src/main/java/com/back2basics/notify/model/NotificationType.java
- module-core/src/main/java/com/back2basics/post/service/PostCreateService.java
- module-core/src/main/java/com/back2basics/post/service/notification/PostNotificationSender.java
- module-core/src/main/java/com/back2basics/project/port/out/ProjectMemberQueryPort.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/assignment/AssignmentEntityRepository.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/ProjectMemberQueryAdapter.java
게시글,댓글에 멘션 기능 추가
기존의 알림 기능을 활용하여 멘션 기능 추가
게시글 생성 시 프로젝트에 할당된 유저들에게 알림 발송
게시글에 답글 생성 시 작성자에게 답글 알림 발송
- Close #366 
- See also #
> [Feature] 게시글,댓글에 멘션 기능 추가

- module-api/src/main/java/com/back2basics/domain/assignment/dto/response/AssignProjectListResponse.java
- module-api/src/main/java/com/back2basics/domain/assignment/dto/response/AssignUserResponse.java
- module-api/src/main/java/com/back2basics/domain/company/dto/response/CompanySummaryResponse.java
- module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
- module-api/src/main/java/com/back2basics/domain/project/dto/response/ProjectDetailResponse.java
- module-api/src/main/java/com/back2basics/domain/project/dto/response/ProjectListResponse.java
- module-api/src/main/java/com/back2basics/domain/projectstep/dto/response/ProjectStepSimpleResponse.java
- module-core/src/main/java/com/back2basics/assignment/service/result/AssignProjectListResult.java
- module-core/src/main/java/com/back2basics/assignment/service/result/AssignUserResult.java
- module-core/src/main/java/com/back2basics/company/service/result/CompanySummaryResult.java
- module-core/src/main/java/com/back2basics/project/port/in/ReadProjectUseCase.java
- module-core/src/main/java/com/back2basics/project/port/out/ReadProjectPort.java
- module-core/src/main/java/com/back2basics/project/service/ReadProjectService.java
- module-core/src/main/java/com/back2basics/project/service/result/ProjectDetailResult.java
- module-core/src/main/java/com/back2basics/project/service/result/ProjectListResult.java
- module-core/src/main/java/com/back2basics/projectstep/service/ReadProjectStepService.java
- module-core/src/main/java/com/back2basics/projectstep/service/result/ProjectStepSimpleResult.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/ReadProjectAdapter.java
- 프로젝트 상세 조회 및 전체 목록 response
- 프로젝트 상세 조회 및 전체 목록 response
- Close #
- See also #
전체 목록 조회 response 살짝 이상해서 다시 수정해서 올릴게요 
회사2 하나만 나와야하는데 두개가 나오네요
> [Refactor] 프로젝트 상세 조회 및 전체 목록 response 수정

- .github/workflows/deploy.yml
> [Deploy] delploy.yml 누락된거 수정

- module-core/src/main/java/com/back2basics/projectstep/service/UpdateProjectStepService.java
- module-core/src/main/java/com/back2basics/projectstep/service/result/ProjectStepResult.java
- projectStep 변수명 변경
- projectStep 변수명 변경
- Close #
- See also #
> [Refactor] projectStep 변수명 변경

- module-api/src/main/java/com/back2basics/domain/board/dto/request/PostUpdateRequest.java
- module-api/src/main/java/com/back2basics/global/security/config/SecurityConfig.java
- module-api/src/main/java/com/back2basics/mongodb/TestController.java
- module-api/src/main/resources/application.yml
- module-core/src/main/java/com/back2basics/board/post/model/Post.java
- module-core/src/main/java/com/back2basics/board/post/port/in/command/PostUpdateCommand.java
- module-infra/build.gradle
- module-infra/src/main/java/com/back2basics/adapter/external/mongodb/TestDocument.java
- module-infra/src/main/java/com/back2basics/adapter/external/mongodb/TestDocumentRepository.java
- module-infra/src/main/java/com/back2basics/adapter/external/mongodb/TestDocumentService.java
게시글 수정에 단계 수정 추가
- Close #400 
- See also #
> [Hotfix] 게시글 수정에 단계 수정 추가

- module-api/src/main/resources/application.yml
dev profiles에만 넣었던 mongodb 설정을 release에도 추가 
- Close #399 
- See also #
> [Build] dev profiles에만 넣었던 mongodb 설정을 release에도 추가 

- module-api/src/main/java/com/back2basics/domain/user/controller/UserController.java
- module-api/src/main/java/com/back2basics/domain/user/dto/response/UserSummaryResponse.java
- module-api/src/main/java/com/back2basics/global/handler/GlobalExceptionHandler.java
- module-api/src/main/resources/application.yml
- module-common/src/main/java/com/back2basics/global/response/code/CommonErrorCode.java
- module-core/src/main/java/com/back2basics/board/post/service/PostCreateService.java
- module-core/src/main/java/com/back2basics/board/post/service/PostUpdateService.java
- module-core/src/main/java/com/back2basics/comment/service/CommentCreateService.java
- module-core/src/main/java/com/back2basics/comment/service/CommentUpdateService.java
- module-core/src/main/java/com/back2basics/mention/MentionNotificationSender.java
- module-core/src/main/java/com/back2basics/mention/MentionUtils.java
- module-core/src/main/java/com/back2basics/notify/model/NotificationType.java
- module-core/src/main/java/com/back2basics/user/port/in/UserSearchUseCase.java
- module-core/src/main/java/com/back2basics/user/port/out/UserQueryPort.java
- module-core/src/main/java/com/back2basics/user/port/out/UserSearchPort.java
- module-core/src/main/java/com/back2basics/user/service/UserSearchService.java
- module-core/src/main/java/com/back2basics/user/service/result/UserSummaryResult.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/user/adapter/out/UserQueryAdapter.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/user/adapter/out/UserSearchAdapter.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/user/repository/UserEntityRepository.java
- module-infra/src/main/java/com/back2basics/config/FileUploadConfig.java
댓글, 게시글 생성/수정 시 멘션 기능 추가, 유저 검색 및 파일 업로드 관련 예외 처리 추가
- 댓글, 게시글 생성/수정 시 멘션 기능 적용
- 멘션알림 처리 클래스가 도메인 ID를 파라미터로 받도록 개선
- `@username` 입력 시 유저 검색 API 구현
- 사용자 검색 결과를 `id, name, username, role`로 리턴하도록 수정
- 파일 업로드 용량 제한 수정 (기존보다 유연하게 처리)
- 파일 용량 초과 시 GlobalExceptionHandler 등록 및 예외 반환 처리
- Close #405 
- Close #406 
- See also #
> [Feature] 댓글, 게시글 생성/수정 시 멘션 기능 추가, 유저 검색 및 파일 업로드 관련 예외 처리 추가

- module-core/src/main/java/com/back2basics/approval/model/ApprovalResponse.java
- module-core/src/main/java/com/back2basics/approval/port/out/ApprovalRequestCommandPort.java
- module-core/src/main/java/com/back2basics/approval/service/CreateApprovalRequestRequestService.java
- module-core/src/main/java/com/back2basics/approval/service/ReadApprovalService.java
- module-core/src/main/java/com/back2basics/approval/service/UpdateApprovalResponseService.java
- module-core/src/main/java/com/back2basics/notify/model/NotificationType.java
- module-core/src/main/java/com/back2basics/user/service/UserSearchService.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/approval/adapter/ApprovalRequestCommandAdapter.java
- 승인 요청 생성 시 알림 전송 기능 구현
- 승인 요청 생성 시 ID 반환 → 알림 전송에 활용 (ReferenceId)
- 승인자 전원 응답 완료 시 상태 자동 변경 (REJECT 우선 처리)
- 단계 상태 변경, 새로운 승인자 추가 시 알림 전송
- enum → description 기반 메시지 처리 리팩토링
- 메서드 네이밍 정리 (save → create)
- 병합 중 발생한 필드 누락 수정
- Close #408 
- See also #
> [Feature] 승인 요청 알림 서비스

- module-api/src/main/java/com/back2basics/domain/user/controller/AdminController.java
- module-core/src/main/java/com/back2basics/user/port/in/UserQueryUseCase.java
- module-core/src/main/java/com/back2basics/user/service/UserQueryService.java
AdminController 모든 유저의 정보를 페이지네이션 하여 조회하는 메서드 수정
UserSimpleResponse에는 email필드가 없어서 조회하고 수정하는 과정에서
수정 모달에 email필드의 정보를 불러오지 못했음.
UserInfoResponse로 타입을 바꿔 email 정보를 불러와 수정할 수 있게 함.
- Close #418 
로컬 환경에서 FE와 연동하여 테스트 정상 동작 확인
> [Feature] 회원 조회 API 수정

- module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
- module-core/src/main/java/com/back2basics/assignment/service/notification/AssignmentNotificationSender.java
- module-core/src/main/java/com/back2basics/notify/model/NotificationType.java
- module-core/src/main/java/com/back2basics/project/service/CreateProjectService.java
- module-core/src/main/java/com/back2basics/project/service/UpdateProjectService.java
- 프로젝트 할당 멤버 알림 전송
- 알림 타입 추가
- sender 작성
- create, update service에 sender 기능 추가
- Close #394 
- See also #
- DB 정상 insert
> [Feature] 프로젝트 할당 멤버 알림 전송

- module-core/src/main/java/com/back2basics/assignment/service/DeleteAssignmentService.java
- module-core/src/main/java/com/back2basics/infra/validation/validator/ProjectStepValidator.java
- module-core/src/main/java/com/back2basics/project/service/CreateProjectService.java
- module-core/src/main/java/com/back2basics/project/service/ReadProjectService.java
- module-core/src/main/java/com/back2basics/project/service/UpdateProjectService.java
- module-core/src/main/java/com/back2basics/projectstep/service/CreateProjectStepService.java
- module-core/src/main/java/com/back2basics/projectstep/service/UpdateProjectStepService.java
- validation 적용
- Close #
- See also #
> [Refactor] validation 적용

- module-api/src/main/java/com/back2basics/domain/project/dto/response/ProjectDetailResponse.java
- module-core/src/main/java/com/back2basics/project/service/result/ProjectDetailResult.java
- detailResponse에 금액 변수 추가
- Close #433 
- See also #
> [Feature] 프로젝트 상세 조회 response 수정

- module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
- module-core/src/main/java/com/back2basics/project/port/in/ReadProjectUseCase.java
- module-core/src/main/java/com/back2basics/project/service/ReadProjectService.java
- 프로젝트 목록 조회 api 통합
-  목록 조회 api 통합
- 로그인 유저 아이디로 도메인 찾기
- 유저의 role에 따라 반환 response 달라짐
- Close #
- See also #
- postman 으로 admin, user 로 로그인 후 조건에 따라  consol 로 분기 잘 나눠지는 지 확인
- postman에서 각 response 값 확인
> [Refactor] 프로젝트 목록 조회 api 통합

- module-api/src/main/java/com/back2basics/domain/company/dto/request/CreateCompanyRequest.java
- module-api/src/main/java/com/back2basics/domain/company/dto/request/UpdateCompanyRequest.java
- module-api/src/main/java/com/back2basics/domain/user/dto/request/UserCreateRequest.java
- module-api/src/main/java/com/back2basics/domain/user/dto/request/UserUpdateRequest.java
회원, 회사 등록 시 전화번호 양식 통일
회원, 회사 등록 시 전화번호 양식 통일
9~11자(번호가 02일 때도 있으니까)
- Close #422
로컬 환경 테스트결과 정상 동작
> [Feature] 회원, 회사 등록 시 전화번호 양식 통일

- module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
- module-api/src/main/java/com/back2basics/domain/project/dto/response/ProjectListResponse.java
- module-core/src/main/java/com/back2basics/project/port/in/ReadProjectUseCase.java
- module-core/src/main/java/com/back2basics/project/port/out/ReadProjectPort.java
- module-core/src/main/java/com/back2basics/project/service/ReadProjectService.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectEntityRepository.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/ReadProjectAdapter.java
- 검색 조회 api 통합
- Close #
- See also #
> [Feature] 검색 조회 api 통합

- module-core/src/main/resources/logback-spring.xml
'module-api/src/main/resources' 경로에 `logback-spring.xml` 작성
- log.error() 등 ERROR 레벨만 파일 출력
- dev, release 프로파일별 경로 분리
- dev는 IntelliJ 내에서 INFO 레벨의 로그가 모두 뜨도록 구성
- Time + Size 기준 분리
- Close #461 
- See also #
> [Docs] Logback XML 파일 추가

- module-core/src/main/resources/logback-spring.xml
로그파일 이름 잘못지정한 실수 수정
다음 내용으로 로그파일 이름 생성(날짜별)
```xml
<fileNamePattern>${LOG_PATH}/release/release.%d{yyyy-MM-dd}.%i.log</fileNamePattern>
```
- Close #461 
- See also #
> [Hotfix] 로그파일 이름 잘못지정한 실수 수정 

- module-core/src/main/java/com/back2basics/company/service/UpdateCompanyService.java
Company 수정 validation 함수 적용
Company 수정 validation 함수 적용
- Close #457
로컬테스트 결과 프론트엔드로 에러 전달 확인 완료
> [Feature] Company 수정 validation 함수 적용

- module-api/src/main/java/com/back2basics/domain/user/controller/AdminController.java
- module-core/src/main/java/com/back2basics/user/port/in/UserQueryUseCase.java
- module-core/src/main/java/com/back2basics/user/port/out/UserQueryPort.java
- module-core/src/main/java/com/back2basics/user/service/UserQueryService.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/user/adapter/out/UserQueryAdapter.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/user/repository/UserEntityRepository.java
회원 전체 조회 api 추가
페이지네이션 적용이 되지않은 회원 전체 조회 api 추가
- Close #470
로컬 환경 테스트 결과 정상 동작
> [Feature] 회원 전체 조회 api 추가

- module-api/src/main/java/com/back2basics/domain/assignment/dto/response/AssignUserResponse.java
- module-api/src/main/java/com/back2basics/domain/project/dto/request/ProjectUpdateRequest.java
- module-api/src/main/java/com/back2basics/domain/project/dto/response/ProjectDetailResponse.java
- module-api/src/main/java/com/back2basics/domain/project/dto/response/ProjectGetResponse.java
- module-core/src/main/java/com/back2basics/assignment/service/result/AssignProjectListResult.java
- module-core/src/main/java/com/back2basics/assignment/service/result/AssignUserResult.java
- module-core/src/main/java/com/back2basics/project/model/Project.java
- module-core/src/main/java/com/back2basics/project/model/ProjectStatus.java
- module-core/src/main/java/com/back2basics/project/port/in/ReadProjectUseCase.java
- module-core/src/main/java/com/back2basics/project/service/CreateProjectService.java
- module-core/src/main/java/com/back2basics/project/service/UpdateProjectService.java
- module-core/src/main/java/com/back2basics/project/service/result/ProjectDetailResult.java
- module-core/src/main/java/com/back2basics/project/service/result/ProjectGetResult.java
- module-core/src/main/java/com/back2basics/project/service/result/ProjectListResult.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectEntity.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectMapper.java
- 변수명 변경 및 response 필드 추가
- projectStatus 변수명 변경
- projectStatus 변경 로직 수정
- 권한별 기능을 위해 detatilResponse에 userType 추가
- Close #
- See also #
> [Refactor] 변수명 변경 및 response 필드 추가

- module-infra/src/main/java/com/back2basics/adapter/persistence/inquiry/InquiryEntityRepository.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/inquiry/adapter/ReadInquiryJpaAdapter.java
전체 조회 시 softDelete된 문의사항은 제외
전체 조회 시 softDelete된 문의사항은 제외
- Close #478
로컬 테스트 결과 정상 동작 확인
> [Feature] 문의사항 전체 조회 api 수정

- module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
- module-api/src/main/java/com/back2basics/domain/project/controller/code/ProjectResponseCode.java
- module-api/src/main/java/com/back2basics/domain/project/dto/response/ProjectCountResponse.java
- module-core/src/main/java/com/back2basics/project/model/Project.java
- module-core/src/main/java/com/back2basics/project/model/StatusCountProjection.java
- module-core/src/main/java/com/back2basics/project/port/in/ReadProjectUseCase.java
- module-core/src/main/java/com/back2basics/project/port/out/ReadProjectPort.java
- module-core/src/main/java/com/back2basics/project/service/ReadProjectService.java
- module-core/src/main/java/com/back2basics/project/service/result/ProjectCountResult.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectEntityRepository.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/ReadProjectAdapter.java
> [Feature] 프로젝트 상태별 개수 조회

- module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
- module-core/src/main/java/com/back2basics/project/port/in/ReadProjectUseCase.java
- module-core/src/main/java/com/back2basics/project/port/out/ReadProjectPort.java
- module-core/src/main/java/com/back2basics/project/service/ReadProjectService.java
- module-core/src/main/java/com/back2basics/user/model/Role.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectEntityRepository.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/ReadProjectAdapter.java
- module-infra/src/main/java/com/back2basics/security/model/CustomUserDetails.java
- 조회 메서드 분기 처리
- 사용하지 않는 role 삭제
- role 값 반환을 위해 getter 어노테이션 추가
- role 값에 따라 조회 메서드 분기 처리
- Close #493 
- See also #
- 역할 분기는 비즈니스 로직에서 처리해야 하므로 service 계층에서 처리했습니다.
> [Feature] 프로젝트 상태 별 조회 분기 처리

- module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectEntityRepository.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/ReadProjectAdapter.java
> [Feature] 조회 시 정렬 옵션 추가 

- module-core/src/main/java/com/back2basics/projectstep/model/ProjectStep.java
- 대기 -> 진행중 추가
- Close #
- See also #
> [Feature] 단계 상태 변경 수정

- module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectEntity.java
- 진행률에 따른 프로젝트 상태변경
- Close #
- See also #
> [Feature] 진행률에 따른 프로젝트 상태변경

- module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
- module-api/src/main/java/com/back2basics/domain/project/controller/code/ProjectResponseCode.java
- module-core/src/main/java/com/back2basics/project/port/in/RestoreProjectUSeCase.java
- module-core/src/main/java/com/back2basics/project/port/out/ReadProjectPort.java
- module-core/src/main/java/com/back2basics/project/service/RestoreProjectService.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectEntityRepository.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/ReadProjectAdapter.java
- 삭제 프로젝트 복구 기능 구현
- Close #
- See also #
> [Feature] 삭제 프로젝트 복구 기능 구현

- module-api/src/main/java/com/back2basics/domain/company/dto/response/ReadCompanyResponse.java
- module-core/src/main/java/com/back2basics/company/model/Company.java
- module-core/src/main/java/com/back2basics/company/service/result/ReadCompanyResult.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/company/CompanyEntityRepository.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/company/CompanyMapper.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/company/dto/CompanyWithUserCountProjection.java
- 회사 조회 시 회사별 회원 수 추가
- 조회 쿼리 수정
- mapper 추가
- userCount 변수 추가
- Close #
- See also #
> [Feature] 회사 조회 시 회사별 회원 수 추가

- module-infra/src/main/java/com/back2basics/adapter/persistence/company/CompanyEntityRepository.java
- 삭제된 사용자 제외한 유저 수 표시
- Close #
- See also #
> [Refactor] 삭제된 사용자를 제외하도록 쿼리 수정

- module-api/src/main/java/com/back2basics/domain/company/dto/request/CreateCompanyRequest.java
- module-api/src/main/java/com/back2basics/domain/company/dto/request/UpdateCompanyRequest.java
Company 사업자 등록번호 정규표현식 수정
앞자리에 0이 들어갈 시, 제대로 된 사업자 등록 번호 양식이 지켜지지않음.
- Close #550
로컬 환경 정상 동작 확인
> [Feature] Company 사업자 등록번호 정규표현식 수정

- module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
- module-core/src/main/java/com/back2basics/assignment/model/Assignment.java
- module-core/src/main/java/com/back2basics/assignment/service/result/AssignProjectListResult.java
- module-core/src/main/java/com/back2basics/assignment/service/result/AssignUserResult.java
- module-core/src/main/java/com/back2basics/assignment/service/result/ReadAssignmentResult.java
- module-core/src/main/java/com/back2basics/company/service/result/CompanySummaryResult.java
- module-core/src/main/java/com/back2basics/infra/validator/ProjectValidator.java
- module-core/src/main/java/com/back2basics/project/service/CreateProjectService.java
- module-core/src/main/java/com/back2basics/project/service/UpdateProjectService.java
- module-core/src/main/java/com/back2basics/project/service/result/ProjectDetailResult.java
- module-core/src/main/java/com/back2basics/project/service/result/ProjectGetResult.java
- module-core/src/main/java/com/back2basics/user/model/User.java
- module-core/src/main/java/com/back2basics/user/service/result/UserCompanyResult.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/assignment/AssignmentMapper.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/ReadProjectAdapter.java
- assigment 도메인에서 다른 도메인을 id 참조로 변경
- assignment 도메인 참조 -> id 참조로 변경
-user 도메인에 company 도메인 삭제
- 각 클래스 로직 수정
- Close #
- See also #
> [Refactor] assigment 도메인에서 다른 도메인을 id 참조로 변경

- module-api/src/main/java/com/back2basics/domain/inquiry/controller/InquiryController.java
- module-core/src/main/java/com/back2basics/answer/service/CreateAnswerService.java
- module-core/src/main/java/com/back2basics/infra/exception/inquiry/InquiryErrorCode.java
- module-core/src/main/java/com/back2basics/infra/validator/InquiryValidator.java
- module-core/src/main/java/com/back2basics/inquiry/port/in/ReadInquiryUseCase.java
- module-core/src/main/java/com/back2basics/inquiry/port/out/ReadInquiryPort.java
- module-core/src/main/java/com/back2basics/inquiry/service/DeleteInquiryService.java
- module-core/src/main/java/com/back2basics/inquiry/service/ReadInquiryService.java
- module-core/src/main/java/com/back2basics/inquiry/service/UpdateInquiryService.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/inquiry/InquiryEntityRepository.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/inquiry/adapter/ReadInquiryJpaAdapter.java
URL을 통해 다른 사용자의 문의사항 조회 되는 현상 수정
하나의 조회 api안에서
관리자 확인을 위한 분기를 만들고
관리자일 경우 id에 따른 조회, 사용자일 경우 사용자 id까지 고려한 조회를 하게 만듦.
- Close #573 
로컬 환경 정상 동작 확인
> [Feature] URL을 통해 다른 사용자의 문의사항 조회 되는 현상 수정

- module-infra/src/main/java/com/back2basics/bulk/AssignmentBulkInitializer.java
> [Etc]: assignments bulk insert 클래스 주석

- module-api/src/main/java/com/back2basics/domain/checklist/controller/ChecklistController.java
- module-api/src/main/java/com/back2basics/domain/checklist/dto/response/ChecklistDetailResponse.java
- module-api/src/main/java/com/back2basics/domain/checklist/dto/response/ChecklistInfoResponse.java
- module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
- module-api/src/main/java/com/back2basics/domain/project/controller/code/ProjectResponseCode.java
- module-api/src/main/java/com/back2basics/domain/project/dto/response/ProjectClientUserResponse.java
- module-core/src/main/java/com/back2basics/checklist/port/in/ReadChecklistUseCase.java
- module-core/src/main/java/com/back2basics/checklist/port/out/ChecklistQueryPort.java
- module-core/src/main/java/com/back2basics/checklist/service/ReadApprovalService.java
- module-core/src/main/java/com/back2basics/checklist/service/ReadChecklistService.java
- module-core/src/main/java/com/back2basics/checklist/service/result/ChecklistDetailResult.java
- module-core/src/main/java/com/back2basics/checklist/service/result/ChecklistInfoResult.java
- module-core/src/main/java/com/back2basics/project/port/in/ReadProjectUseCase.java
- module-core/src/main/java/com/back2basics/project/service/ReadProjectService.java
- module-core/src/main/java/com/back2basics/project/service/result/ProjectClientUserResult.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/checklist/adapter/ChecklistQueryAdapter.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/checklist/repository/ChecklistEntityRepository.java
- 고객사 정보 조회 기능 추가 및 체크리스트 관련 반환 값 리팩터링
- 프로젝트에 할당된 고객사 정보 조회 API 연동 (GET /project/:id/customers)
- API 응답 형태에 맞게 반환 값 리팩터링
- 기존 로직 정리 및 타입/구조 정비
- Close #557 
- See also #
> [Feature] 고객사 정보 조회 기능 추가 및 체크리스트 관련 반환 값 리팩터링

- module-infra/src/main/java/com/back2basics/adapter/persistence/inquiry/InquirySpecifications.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/inquiry/adapter/ReadInquiryJpaAdapter.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/user/UserSpecifications.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/user/adapter/out/UserQueryAdapter.java
필터링 api deletedAt IS NULL인 것 만 검색되게 수정
필터링 api deletedAt IS NULL인 것 만 검색되게 수정
- Close #587
> [Feature] 필터링 api deletedAt IS NULL인 것 만 검색되게 수정

- module-batch/src/main/java/com/back2basics/ProjectStatusBatchScheduler.java
- module-core/src/main/java/com/back2basics/project/model/Project.java
- module-core/src/main/java/com/back2basics/project/port/in/UpdateProjectUseCase.java
- module-core/src/main/java/com/back2basics/project/port/out/ReadProjectPort.java
- module-core/src/main/java/com/back2basics/project/service/UpdateProjectService.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/project/ProjectEntityRepository.java
- module-infra/src/main/java/com/back2basics/adapter/persistence/project/adapter/ReadProjectAdapter.java
- 프로젝트 마감일과 진행률 기준으로 상태를 자동 업데이트하는 기능을 도메인/스케줄러에 구현했습니다. 매일 새벽 1시에 실행됩니다.
- 프로젝트 도메인에 상태 변경 메서드 evaluateStatus() 추가
- 마감일 기준으로 DUE_SOON, DELAY, IN_PROGRESS, COMPLETED 상태 자동 판별
- 상태 변경 로직을 포함한 도메인 usecase (updateDueSoonAndDelayedProjects) 구현
- 매일 새벽 1시 자동 실행되는 스케줄러 추가 (@Scheduled 기반)
- Close #601 
- See also #
> [Feature] 프로젝트 상태 자동 변경 기능 구현

- module-api/src/main/java/com/back2basics/custom/CustomUserDistinctCheck.java
- module-api/src/main/java/com/back2basics/custom/CustomUserDistinctCheckValidator.java
- module-api/src/main/java/com/back2basics/custom/ManagerIncludedInUserCheck.java
- module-api/src/main/java/com/back2basics/custom/ManagerIncludedInUserCheckValidator.java
- module-api/src/main/java/com/back2basics/domain/project/controller/ProjectController.java
- module-api/src/main/java/com/back2basics/domain/project/dto/request/ProjectCreateRequest.java
- module-api/src/main/java/com/back2basics/domain/project/dto/request/ProjectUpdateRequest.java
- module-api/src/main/java/com/back2basics/domain/project/dto/request/UserDistinctCheckDto.java
- module-core/src/main/java/com/back2basics/project/service/CreateProjectService.java
- module-core/src/main/java/com/back2basics/project/service/DeleteProjectService.java
- module-core/src/main/java/com/back2basics/project/service/RestoreProjectService.java
- module-core/src/main/java/com/back2basics/project/service/UpdateProjectService.java
프로젝트 생성 및 수정 시, 요청 데이터에 대한 검증 어노테이션을 추가했습니다.  
- `ProjectCreateRequest`에 `@NotBlank`, `@NotNull`, `@Size` 등 검증 어노테이션 추가
- `ProjectUpdateRequest`에도 동일한 검증 어노테이션 적용
- `@Valid`를 통해 Controller 단에서 유효성 검사 수행
- 잘못된 입력에 대해 적절한 예외 메시지를 반환하도록 설정
- 테스트 케이스는 기존 로직을 기반으로 그대로 작동함을 확인
- 추후 글로벌 예외 핸들링에 메시지 정제 필요 여부 검토 예정
- Close #
- See also #
> [Refactor] 프로젝트 생성, 수정 검증 어노테이션 추가
